server:
  port: 0

spring:
  application:
    name: stats-server

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true