server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: main-service
          uri: lb://MAIN-SERVICE
          predicates:
            - Path=/**
    loadbalancer:
      retry:
        enabled: true
      cache:
        enabled: true
        ttl: 10s