# ????, ?? ??????? ????? ??????? Gateway (????????????? 8080)
server.port=8080

# ???????? ?????????????? ???????? ????????? ?? ?????? ?????????????????? ????????
spring.cloud.gateway.discovery.locator.enabled=true
# ???????? ????? ???????? ? ??????? ???????? ??? URL (????????, main-service)
spring.cloud.gateway.discovery.locator.lower-case-service-id=true